#!/usr/bin/env bash
# PreToolUse hook: block Write/Edit on auto-generated files.
# These files are managed by build tools and package managers — manual edits will be overwritten.
#
# Blocked files:
#   package-lock.json       — auto-generated by npm install
#   gradlew, gradlew.bat   — Gradle Wrapper scripts
#   gradle/wrapper/*        — Gradle Wrapper config
#   tsconfig.tsbuildinfo    — TypeScript build cache
#   .next/*                 — Next.js build output
#   node_modules/*          — npm packages
#
# Exit codes:
#   0 = allow (not an auto-generated file)
#   2 = block (auto-generated file detected, message shown to user)
#
# Fail-open: if JSON parsing fails, exit 0 so normal operations are not disrupted.

set -euo pipefail

# Parse PreToolUse JSON from stdin
read -r INPUT 2>/dev/null || exit 0

FILE_PATH=$(python3 -c "
import json, sys
data = json.loads(sys.argv[1])
print(data.get('tool_input', {}).get('file_path', ''))
" "$INPUT" 2>/dev/null) || exit 0

# Exit if no file path found
[[ -z "$FILE_PATH" ]] && exit 0

# Normalize to basename for pattern matching
BASENAME=$(basename "$FILE_PATH")

# --- Block auto-generated basename patterns ---
case "$BASENAME" in
  # Lock files
  package-lock.json)
    echo "BLOCKED: '$BASENAME' is auto-generated by npm install. Run 'npm install' to update it." >&2
    exit 2
    ;;
  # Gradle Wrapper scripts
  gradlew | gradlew.bat)
    echo "BLOCKED: '$BASENAME' is auto-generated by Gradle Wrapper. Use 'gradle wrapper' to update it." >&2
    exit 2
    ;;
  # TypeScript build cache
  tsconfig.tsbuildinfo)
    echo "BLOCKED: '$BASENAME' is a TypeScript build cache. It is auto-generated by tsc." >&2
    exit 2
    ;;
esac

# --- Block auto-generated path patterns ---
case "$FILE_PATH" in
  # Gradle Wrapper config directory
  */gradle/wrapper/*)
    echo "BLOCKED: Gradle Wrapper files are auto-generated. Use 'gradle wrapper' to update." >&2
    exit 2
    ;;
  # Next.js build output
  */.next/*)
    echo "BLOCKED: '.next/' is the Next.js build output directory. Run 'npm run build' instead." >&2
    exit 2
    ;;
  # npm packages
  */node_modules/*)
    echo "BLOCKED: 'node_modules/' contains installed packages. Use 'npm install' to manage." >&2
    exit 2
    ;;
esac

exit 0
