package com.worklog.api;

import com.worklog.application.service.UserStatusService;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpSession;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import java.util.UUID;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/v1/user")
public class UserStatusController {

    private final UserStatusService userStatusService;

    public UserStatusController(UserStatusService userStatusService) {
        this.userStatusService = userStatusService;
    }

    @GetMapping("/status")
    @PreAuthorize("isAuthenticated()")
    public UserStatusService.UserStatusResponse getStatus(Authentication authentication) {
        return userStatusService.getUserStatus(authentication.getName());
    }

    @PostMapping("/select-tenant")
    @PreAuthorize("isAuthenticated()")
    public ResponseEntity<Void> selectTenant(
            @RequestBody @Valid SelectTenantRequest request,
            Authentication authentication,
            HttpServletRequest httpRequest) {
        // The session_id in user_sessions is a UUID generated by UserSession.create(),
        // stored as an HttpSession attribute during login (see AuthController.login()).
        HttpSession session = httpRequest.getSession(false);
        if (session == null) {
            return ResponseEntity.badRequest().build();
        }

        Object sessionIdAttr = session.getAttribute("sessionId");
        if (sessionIdAttr == null) {
            return ResponseEntity.badRequest().build();
        }

        // The sessionId attribute is stored as a String UUID by AuthController
        UUID sessionId;
        if (sessionIdAttr instanceof UUID uuid) {
            sessionId = uuid;
        } else {
            sessionId = UUID.fromString(sessionIdAttr.toString());
        }

        userStatusService.selectTenant(authentication.getName(), request.tenantId(), sessionId);

        return ResponseEntity.ok().build();
    }

    public record SelectTenantRequest(@NotNull UUID tenantId) {}
}
